name: Note Taking CI

on:
  push:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: create env file
        run: cp .env.example .env

      - name: Install Dependencies
        run: npm ci

      - name: run Lint check
        run: npm run lint

      - name: run test cases
        run: npm run test
        env:
          CI: true
          NODE_ENV: test
